### ISSUE TITLE
Livingstyleguide fails when using foundation

### ISSUE THREAD

**Issue by RalphAtHamburg** [livingstyleguide/examples#2]
I have a rails 4 app using foundation 5 (gem 'foundation-rails').
The line `import "foundation"` 
inside `application.css.scss` breaks the Livingstyleguide.

File to import not found or unreadable: foundation. Load paths: LivingStyleGuide::VariablesImporter Compass::SpriteImporter /Users/ralph/Development/livingstyleguide-example/rails-example/app/assets/stylesheets /Users/ralph/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/compass-0.12.2/frameworks/blueprint/stylesheets /Users/ralph/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/compass-0.12.2/frameworks/compass/stylesheets /Users/ralph/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/livingstyleguide-0.6.0.alpha.1/stylesheets (in /Users/ralph/Development/livingstyleguide-example/rails-example/app/assets/stylesheets/styleguide.html.lsg)

**Comment by hagenburger** [comment]
I can reproduce it and moved it into the gem’s repository: https://github.com/hagenburger/livingstyleguide/issues/17

As a quick fix, can you manually add the load path?
